# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170611_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='blog.Tag'),
        ),
    ]
