# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170611_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
