# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 04:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb_width',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=blog.models.get_image_filename, verbose_name='Image'),
        ),
    ]
